services:
  flask_app:
    build: .
    container_name: flask_app
    expose:
      - "8000"
    env_file:
      - .env
    mem_limit: 2048M
    cpus: 1.0
    restart: always
    volumes:
      - ./gunicorn_config.py:/app/gunicorn_config.py
    command: ["gunicorn", "--config", "/app/gunicorn_config.py", "service.app:create_app()"]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask_app
    mem_limit: 512M
    cpus: 0.5
    restart: always